In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
import pandas as pd
seed_files = {
    'seed_1perc': '/content/drive/MyDrive/THESIS/05outputs/dev_seed_1percent.csv',
    'seed_5perc': '/content/drive/MyDrive/THESIS/05outputs/dev_seed_5percent.csv',
    'seed_10perc': '/content/drive/MyDrive/THESIS/05outputs/dev_seed_10percent.csv',
    'seed_20perc': '/content/drive/MyDrive/THESIS/05outputs/dev_seed_20percent.csv'
}

seed_dfs = {}
for name, path in seed_files.items():
    try:
        seed_dfs[name] = pd.read_csv(path)
        print(f"Loaded {name}: {len(seed_dfs[name])} rows")
    except FileNotFoundError:
        print(f"Warning: Seed file not found at {path}")

print("Seed files loaded.")

Loaded seed_1perc: 50 rows
Loaded seed_5perc: 247 rows
Loaded seed_10perc: 493 rows
Loaded seed_20perc: 985 rows
Seed files loaded.

### Applying SMOTE (Synthetic Minority Over-sampling Technique)

SMOTE is an oversampling technique used to address imbalanced datasets by generating synthetic samples from the minority class. This helps in training machine learning models more effectively when one class is significantly underrepresented.

In [19]:
# Install imbalanced-learn if not already installed
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [20]:
import pandas as pd
from collections import Counter
from imblearn.over_sampling import SMOTE

TARGET_COLUMN_NAME = 'Churn Value'

if TARGET_COLUMN_NAME in seed_dfs['seed_1perc'].columns:
    X = seed_dfs['seed_1perc'].drop(TARGET_COLUMN_NAME, axis=1)
    y = seed_dfs['seed_1perc'][TARGET_COLUMN_NAME]

    print(f"Original dataset shape: {Counter(y)}")

    # Modify SMOTE to generate approximately 5000 rows (2500 per class)
    # The sampling_strategy dictionary specifies the desired number of samples for each class after resampling.
    sm = SMOTE(sampling_strategy={0: 2500, 1: 2500}, random_state=42)
    X_res, y_res = sm.fit_resample(X, y)

    print(f"Resampled dataset shape: {Counter(y_res)}")

    # Create a new DataFrame with the SMOTE-resampled data
    seed_1perc_smoted = pd.DataFrame(X_res, columns=X.columns)
    seed_1perc_smoted[TARGET_COLUMN_NAME] = y_res

    print("\nFirst 5 rows of the SMOTE-resampled data:")
    display(seed_1perc_smoted.head())
    print(f"Total rows in resampled DataFrame: {len(seed_1perc_smoted)}")
else:
    print(f"Error: The column '{TARGET_COLUMN_NAME}' was not found in the DataFrame. Please check the column name.")

Original dataset shape: Counter({0: 38, 1: 12})
Resampled dataset shape: Counter({0: 2500, 1: 2500})

First 5 rows of the SMOTE-resampled data:

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Internet Service_Fiber optic,Internet Service_No,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Churn Value
0,1,0,1,0,1.164390,1,1,0,0,0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
1,1,1,1,0,1.327365,1,0,0,0,0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0
2,1,1,1,0,1.531085,1,1,1,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
3,0,0,1,1,0.227279,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0,0,1,1,-0.750577,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0

Total rows in resampled DataFrame: 5000

The `seed_1perc` DataFrame has now been oversampled using SMOTE, and the class distribution of the 'Churn' variable should be balanced.

In [21]:
output_path = '/content/drive/MyDrive/THESIS/05outputs/resultSMOTE1p.csv'
seed_1perc_smoted.to_csv(output_path, index=False)
print(f"SMOTEd data saved to: {output_path}")

SMOTEd data saved to: /content/drive/MyDrive/THESIS/05outputs/resultSMOTE1p.csv

### Applying SMOTE to `seed_5perc`

In [22]:
TARGET_COLUMN_NAME = 'Churn Value'

if TARGET_COLUMN_NAME in seed_dfs['seed_5perc'].columns:
    X = seed_dfs['seed_5perc'].drop(TARGET_COLUMN_NAME, axis=1)
    y = seed_dfs['seed_5perc'][TARGET_COLUMN_NAME]

    print(f"Original dataset shape for seed_5perc: {Counter(y)}")

    # Apply SMOTE to generate approximately 5000 rows (2500 per class)
    sm = SMOTE(sampling_strategy={0: 2500, 1: 2500}, random_state=42)
    X_res, y_res = sm.fit_resample(X, y)

    print(f"Resampled dataset shape for seed_5perc: {Counter(y_res)}")

    # Create a new DataFrame with the SMOTE-resampled data
    seed_5perc_smoted = pd.DataFrame(X_res, columns=X.columns)
    seed_5perc_smoted[TARGET_COLUMN_NAME] = y_res

    print("\nFirst 5 rows of the SMOTE-resampled data for seed_5perc:")
    display(seed_5perc_smoted.head())
    print(f"Total rows in resampled DataFrame for seed_5perc: {len(seed_5perc_smoted)}")
else:
    print(f"Error: The column '{TARGET_COLUMN_NAME}' was not found in the seed_5perc DataFrame. Please check the column name.")

Original dataset shape for seed_5perc: Counter({0: 181, 1: 66})
Resampled dataset shape for seed_5perc: Counter({0: 2500, 1: 2500})

First 5 rows of the SMOTE-resampled data for seed_5perc:

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Internet Service_Fiber optic,Internet Service_No,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Churn Value
0,1,0,1,0,1.164390,1,1,0,0,0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
1,1,1,1,0,1.327365,1,0,0,0,0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0
2,1,1,1,0,1.531085,1,1,1,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
3,0,0,1,1,0.227279,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0,0,1,1,-0.750577,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0

Total rows in resampled DataFrame for seed_5perc: 5000

In [23]:
output_path_5perc = '/content/drive/MyDrive/THESIS/05outputs/resultSMOTE5p.csv'
seed_5perc_smoted.to_csv(output_path_5perc, index=False)
print(f"SMOTEd data for seed_5perc saved to: {output_path_5perc}")

SMOTEd data for seed_5perc saved to: /content/drive/MyDrive/THESIS/05outputs/resultSMOTE5p.csv

### Applying SMOTE to `seed_10perc`

In [24]:
TARGET_COLUMN_NAME = 'Churn Value'

if TARGET_COLUMN_NAME in seed_dfs['seed_10perc'].columns:
    X = seed_dfs['seed_10perc'].drop(TARGET_COLUMN_NAME, axis=1)
    y = seed_dfs['seed_10perc'][TARGET_COLUMN_NAME]

    print(f"Original dataset shape for seed_10perc: {Counter(y)}")

    # Apply SMOTE to generate approximately 5000 rows (2500 per class)
    sm = SMOTE(sampling_strategy={0: 2500, 1: 2500}, random_state=42)
    X_res, y_res = sm.fit_resample(X, y)

    print(f"Resampled dataset shape for seed_10perc: {Counter(y_res)}")

    # Create a new DataFrame with the SMOTE-resampled data
    seed_10perc_smoted = pd.DataFrame(X_res, columns=X.columns)
    seed_10perc_smoted[TARGET_COLUMN_NAME] = y_res

    print("\nFirst 5 rows of the SMOTE-resampled data for seed_10perc:")
    display(seed_10perc_smoted.head())
    print(f"Total rows in resampled DataFrame for seed_10perc: {len(seed_10perc_smoted)}")
else:
    print(f"Error: The column '{TARGET_COLUMN_NAME}' was not found in the seed_10perc DataFrame. Please check the column name.")

Original dataset shape for seed_10perc: Counter({0: 362, 1: 131})
Resampled dataset shape for seed_10perc: Counter({0: 2500, 1: 2500})

First 5 rows of the SMOTE-resampled data for seed_10perc:

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Internet Service_Fiber optic,Internet Service_No,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Churn Value
0,1,0,1,0,1.164390,1,1,0,0,0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
1,1,1,1,0,1.327365,1,0,0,0,0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0
2,1,1,1,0,1.531085,1,1,1,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
3,0,0,1,1,0.227279,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0,0,1,1,-0.750577,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0

Total rows in resampled DataFrame for seed_10perc: 5000

In [25]:
output_path_10perc = '/content/drive/MyDrive/THESIS/05outputs/resultSMOTE10p.csv'
seed_10perc_smoted.to_csv(output_path_10perc, index=False)
print(f"SMOTEd data for seed_10perc saved to: {output_path_10perc}")

SMOTEd data for seed_10perc saved to: /content/drive/MyDrive/THESIS/05outputs/resultSMOTE10p.csv

### Applying SMOTE to `seed_20perc`

In [26]:
TARGET_COLUMN_NAME = 'Churn Value'

if TARGET_COLUMN_NAME in seed_dfs['seed_20perc'].columns:
    X = seed_dfs['seed_20perc'].drop(TARGET_COLUMN_NAME, axis=1)
    y = seed_dfs['seed_20perc'][TARGET_COLUMN_NAME]

    print(f"Original dataset shape for seed_20perc: {Counter(y)}")

    # Apply SMOTE to generate approximately 5000 rows (2500 per class)
    sm = SMOTE(sampling_strategy={0: 2500, 1: 2500}, random_state=42)
    X_res, y_res = sm.fit_resample(X, y)

    print(f"Resampled dataset shape for seed_20perc: {Counter(y_res)}")

    # Create a new DataFrame with the SMOTE-resampled data
    seed_20perc_smoted = pd.DataFrame(X_res, columns=X.columns)
    seed_20perc_smoted[TARGET_COLUMN_NAME] = y_res

    print("\nFirst 5 rows of the SMOTE-resampled data for seed_20perc:")
    display(seed_20perc_smoted.head())
    print(f"Total rows in resampled DataFrame for seed_20perc: {len(seed_20perc_smoted)}")
else:
    print(f"Error: The column '{TARGET_COLUMN_NAME}' was not found in the seed_20perc DataFrame. Please check the column name.")

Original dataset shape for seed_20perc: Counter({0: 714, 1: 271})
Resampled dataset shape for seed_20perc: Counter({0: 2500, 1: 2500})

First 5 rows of the SMOTE-resampled data for seed_20perc:

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Internet Service_Fiber optic,Internet Service_No,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Churn Value
0,1,0,1,0,1.164390,1,1,0,0,0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
1,1,1,1,0,1.327365,1,0,0,0,0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0
2,1,1,1,0,1.531085,1,1,1,1,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
3,0,0,1,1,0.227279,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
4,0,0,1,1,-0.750577,1,0,0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0

Total rows in resampled DataFrame for seed_20perc: 5000

In [27]:
output_path_20perc = '/content/drive/MyDrive/THESIS/05outputs/resultSMOTE20p.csv'
seed_20perc_smoted.to_csv(output_path_20perc, index=False)
print(f"SMOTEd data for seed_20perc saved to: {output_path_20perc}")

SMOTEd data for seed_20perc saved to: /content/drive/MyDrive/THESIS/05outputs/resultSMOTE20p.csv